/**
 * Result Exporter
 * Generates and downloads Markdown reports for grading results.
 */
class ResultExporter {
  /**
   * Format current date and time as YYYYMMDD_HHMM
   */
  static getTimestampString(date = new Date()) {
    const pad = (n) => String(n).padStart(2, '0');
    const yyyy = date.getFullYear();
    const mm = pad(date.getMonth() + 1);
    const dd = pad(date.getDate());
    const hh = pad(date.getHours());
    const min = pad(date.getMinutes());
    return `${yyyy}${mm}${dd}_${hh}${min}`;
  }

  /**
   * Format readable date and time string
   */
  static getReadableDate(date = new Date()) {
    const pad = (n) => String(n).padStart(2, '0');
    const yyyy = date.getFullYear();
    const mm = pad(date.getMonth() + 1);
    const dd = pad(date.getDate());
    const hh = pad(date.getHours());
    const min = pad(date.getMinutes());
    const ss = pad(date.getSeconds());
    return `${yyyy}-${mm}-${dd} ${hh}:${min}:${ss}`;
  }

  /**
   * Generate Markdown content string for the test result
   */
  static generateMarkdown(problem, code, overallVerdict, results) {
    const now = new Date();
    const formattedDate = this.getReadableDate(now);
    
    let md = `# [채점 결과] ${problem.id}. ${problem.title}\n\n`;
    md += `## 1. 기본 정보\n`;
    md += `- **제출 일시**: ${formattedDate}\n`;
    md += `- **문제 번호**: ${problem.id}\n`;
    md += `- **문제 제목**: ${problem.title}\n`;
    md += `- **난이도**: ${problem.difficulty}\n`;
    md += `- **시간 / 메모리 제한**: ${problem.time_limit} / ${problem.memory_limit}\n`;
    md += `- **최종 판정**: **${overallVerdict.label}**\n\n`;

    md += `## 2. 테스트케이스 채점 상세\n\n`;
    if (results && results.length > 0) {
      md += `| 번호 | 결과 | 실행 시간 | 세부 내용 |\n`;
      md += `| :--- | :--- | :--- | :--- |\n`;
      results.forEach((r, idx) => {
        const time = r.timeMs !== undefined ? `${r.timeMs}ms` : '-';
        const notes = r.status === 'PASSED' ? '정답' : (r.status === 'COMPILE_ERROR' ? '컴파일 에러' : (r.status === 'RUNTIME_ERROR' ? '런타임 에러' : (r.status === 'TIME_LIMIT_EXCEEDED' ? '시간 초과' : '오답')));
        md += `| 예제 ${idx + 1} | ${r.label} | ${time} | ${notes} |\n`;
      });
      md += `\n`;

      // Detailed diff / errors if any
      const failedCases = results.filter(r => r.status !== 'PASSED');
      if (failedCases.length > 0) {
        md += `### 불일치 및 에러 상세\n\n`;
        failedCases.forEach((r, idx) => {
          md += `#### 예제 ${idx + 1} (${r.label})\n`;
          if (r.error) {
            md += `**에러/경고 메시지:**\n\`\`\`\n${r.error.trim()}\n\`\`\`\n\n`;
          }
          if (r.input) {
            md += `**입력값:**\n\`\`\`\n${r.input}\n\`\`\`\n\n`;
          }
          if (r.expected !== undefined) {
            md += `**기대 출력:**\n\`\`\`\n${r.expected}\n\`\`\`\n\n`;
          }
          if (r.actual) {
            md += `**실제 출력:**\n\`\`\`\n${r.actual}\n\`\`\`\n\n`;
          }
        });
      }
    } else {
      md += `(실행된 테스트케이스가 없습니다)\n\n`;
    }

    md += `## 3. 제출 코드 (C++)\n\n`;
    md += `\`\`\`cpp\n${code.trim()}\n\`\`\`\n\n`;
    md += `---\n*Generated by PRICOTE (Client-side C++ Coding Test Judge)*\n`;

    return md;
  }

  /**
   * Export and trigger browser download
   */
  static exportResult(problem, code, overallVerdict, results) {
    const mdContent = this.generateMarkdown(problem, code, overallVerdict, results);
    const timestamp = this.getTimestampString();
    const safeProblemId = String(problem.id || 'problem').replace(/[^a-zA-Z0-9_-]/g, '_');
    const filename = `result_${safeProblemId}_${timestamp}.md`;

    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);

    return filename;
  }
}

window.ResultExporter = ResultExporter;
